name: WoolWars
version: '${project.version}'
main: com.github.firewolf8385.woolwars.WoolWars
api-version: 1.18
authors: [ firewolf8385 ]
description: Fun Team Based Minigame Based Off Hypixel's Wool Wars

depend:
  - PlaceholderAPI

commands:
  party:
    description: Main party command.
    aliases: [p]
  partychat:
    description: Alias for /party chat.
    aliases: [pc]
  woolwars:
    description: Main Wool Wars command.
    aliases: [ww]